#!/usr/bin/env python3
"""
EEG Data Analysis Script using MNE-Python.
- Loads data from a CSV file generated by ble_receiver.py.
- Creates an MNE Raw object.
- Computes and plots the Power Spectral Density (PSD).
- Calculates and displays quantitative metrics for signal quality assessment.
"""

import sys
import pandas as pd
import mne
import numpy as np
import matplotlib.pyplot as plt

# --- 評価指標の計算に関する設定 ---
SAMPLING_FREQ = 250  # Hz (デバイスの設定と一致させること)

# LSBからマイクロボルトへの変換係数
# ADS1299のデータシートより: V_ref=4.5V, Gain=24x.
# スケール係数 = (V_ref / Gain) / (2^15)
# 今回はuVで計算するため、1e6を乗算
SCALING_FACTOR = (4.5 / 24.0) / (2**15) * 1e6 # uV/LSB

# 電源ノイズの周波数 (お住まいの地域に合わせて50または60に変更)
POWER_LINE_FREQ = 50.0  # Hz (e.g., 50 for East Japan, 60 for West Japan)

# --- 評価の閾値 ---
# 標準偏差がこの値 (uV) より小さい場合、接触不良の可能性を警告
STD_DEV_THRESHOLD_LOW = 1.0
# 標準偏差がこの値 (uV) より大きい場合、体動ノイズの可能性を警告
STD_DEV_THRESHOLD_HIGH = 200.0
# 電源ノイズ比がこの値より大きい場合、ノイズが多いと判断
POWER_LINE_RATIO_THRESHOLD = 5.0
# 高周波ノイズ比がこの値より大きい場合、筋電ノイズの可能性を警告
HIGH_FREQ_RATIO_THRESHOLD = 1.0


def analyze_eeg_data(filepath: str):
    """CSVファイルからEEGデータを読み込み、処理・分析・評価を行う"""
    print(f"--- Analyzing EEG Data from: {filepath} ---")

    try:
        df = pd.read_csv(filepath)
    except FileNotFoundError:
        print(f"Error: File not found at '{filepath}'")
        return

    # --- 1. データ準備 ---
    ch_names = [col for col in df.columns if col not in ['timestamp', 'sample_index', 'trigger']]
    num_channels = len(ch_names)
    print(f"Found {num_channels} channels: {ch_names}")

    # EEGデータを抽出し、LSBからマイクロボルト(uV)に変換
    eeg_data_uv = df[ch_names].values.T * SCALING_FACTOR
    # MNEはボルト(V)単位を要求するため、さらに1e-6を乗算
    eeg_data_volts = eeg_data_uv * 1e-6
    
    # --- 2. MNE Rawオブジェクトの作成 ---
    info = mne.create_info(ch_names=ch_names, sfreq=SAMPLING_FREQ, ch_types='eeg')
    raw = mne.io.RawArray(eeg_data_volts, info)
    print("\n--- MNE Raw object created successfully ---")
    print(raw)

    # --- 3. PSDの計算とプロット ---
    print("\n--- Plotting Power Spectral Density (PSD) ---")
    print("Close the plot window to continue...")
    psd_fig = raw.compute_psd(fmax=100).plot(picks='eeg', average=False, spatial_colors=True)
    plt.show()

    # --- 4. 定量的な信号品質評価 ---
    print("\n--- Quantitative Signal Quality Assessment ---")
    
    # 全チャンネルのPSDデータを取得
    psds, freqs = raw.compute_psd(fmin=1.0, fmax=100.0).get_data(return_freqs=True)
    
    # 結果を格納するリスト
    quality_results = []

    for i, ch_name in enumerate(ch_names):
        # --- 指標1: 標準偏差 (Standard Deviation) ---
        # 目的: 信号の全体的な振幅を評価する。小さすぎる(フラット)または大きすぎる(体動)チャンネルを検出。
        # 計算方法: チャンネルの全データ点の標準偏差を計算する。
        std_dev = np.std(eeg_data_uv[i, :])
        if std_dev < STD_DEV_THRESHOLD_LOW:
            std_status = "FLAT (接触不良?)"
        elif std_dev > STD_DEV_THRESHOLD_HIGH:
            std_status = "HIGH (体動ノイズ?)"
        else:
            std_status = "OK"

        # --- 指標2: 電源ノイズ比 (Power-Line Noise Ratio) ---
        # 目的: 50/60Hzの電源ノイズの混入レベルを評価する。
        # 計算方法: 電源周波数周辺のパワーの平均と、そのすぐ外側の周波数帯のパワーの平均との比率を計算する。
        noise_band = (freqs >= POWER_LINE_FREQ - 1) & (freqs <= POWER_LINE_FREQ + 1)
        signal_band1 = (freqs >= POWER_LINE_FREQ - 3) & (freqs <= POWER_LINE_FREQ - 1.5)
        signal_band2 = (freqs >= POWER_LINE_FREQ + 1.5) & (freqs <= POWER_LINE_FREQ + 3)
        
        power_noise = np.mean(psds[i, noise_band])
        power_signal = np.mean(np.concatenate((psds[i, signal_band1], psds[i, signal_band2])))
        
        pln_ratio = power_noise / power_signal if power_signal > 1e-12 else 0
        pln_status = "NOISY" if pln_ratio > POWER_LINE_RATIO_THRESHOLD else "OK"

        # --- 指標3: 高周波ノイズ比 (High-Frequency Noise Ratio) ---
        # 目的: 筋電(EMG)など、比較的高周波のノイズ成分の割合を評価する。
        # 計算方法: 主要脳波帯域(1-30Hz)のパワーと高周波帯域(30-100Hz)のパワーの比率を計算する。
        eeg_band = (freqs >= 1.0) & (freqs < 30.0)
        hf_band = (freqs >= 30.0) & (freqs < 100.0)

        power_eeg = np.mean(psds[i, eeg_band])
        power_hf = np.mean(psds[i, hf_band])
        
        hf_ratio = power_hf / power_eeg if power_eeg > 1e-12 else 0
        hf_status = "HIGH (筋電ノイズ?)" if hf_ratio > HIGH_FREQ_RATIO_THRESHOLD else "OK"

        quality_results.append({
            "Channel": ch_name,
            "Std Dev (uV)": f"{std_dev:.1f}",
            "Std Status": std_status,
            "PLN Ratio": f"{pln_ratio:.1f}",
            "PLN Status": pln_status,
            "HF Ratio": f"{hf_ratio:.2f}",
            "HF Status": hf_status,
        })

    # --- 結果を表形式で表示 ---
    # ヘッダーの作成と表示
    headers = quality_results[0].keys()
    header_str = f"{' | '.join(f'{h:<20}' for h in headers)}"
    print(header_str)
    print("-" * len(header_str))

    # 各チャンネルの結果を表示
    for result in quality_results:
        row_str = f"{' | '.join(f'{str(v):<20}' for v in result.values())}"
        print(row_str)

    print("\n--- Analysis Complete ---")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("Usage: python analyze_eeg.py <path_to_your_eeg_data.csv>")
        sys.exit(1)
    
    csv_file_path = sys.argv[1]
    analyze_eeg_data(csv_file_path)

